name: woop
description: Projeto de redesign do aplicativo Woop Sicredi

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.5
  sqflite: ^2.1.0
  iconsax: ^0.0.8
  latlong2: ^0.8.1
  line_icons: ^2.0.1
  qr_flutter: ^4.0.0
  flutter_map: ^3.0.0
  url_launcher: ^6.1.6
  qr_code_vision: ^0.1.0
  pretty_qr_code: ^2.0.2
  cupertino_icons: ^1.0.5
  connectivity_plus: ^2.3.7
  animated_text_kit: ^4.2.2
  particles_flutter: ^0.1.4
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.10+1
  flutter_adaptive_scaffold: ^0.0.5
  infinite_scroll_pagination: ^3.2.0
  flutter_map_location_marker: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
